dist: xenial

language: python
python:
  - {{cookiecutter.python_major_version}}.{{cookiecutter.python_minor_version}}

cache:
  pip: true
  directories:
    - ${VIRTUAL_ENV}

env:
  global:
    - RANDOM_SEED=0

before_install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - make doctor

install:
  - make install

script:
  - make check
  - make test

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: never
