site_name: {{cookiecutter.project_name}}
site_description: {{cookiecutter.project_short_description}}
site_author: {{cookiecutter.full_name}}

repo_url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repo}}
edit_uri: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repo}}/edit/{{cookiecutter.default_branch}}/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
