site_name: {{cookiecutter.project_name}}
site_description: {{cookiecutter.project_short_description}}
site_author: {{cookiecutter.full_name}}
repo_url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.github_repo}}

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
